baseURL = "http://interactives.ctl.columbia.edu/"
copyright = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Interactives \u0040 CTL"
SectionPagesMenu = "main"

[taxonomies]
    tag = "tags"

[params]
    description = "Interactives@CTL is a collection of rich client-side Javascript interactive content developed at Columbia's Center for Teaching and Learning (CTL)."
    keywords = "javascript, webpack"